services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      email-checker-app-1:
        condition: service_healthy
      email-checker-app-2:
        condition: service_healthy
      email-checker-app-3:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  email-checker-app-1:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - "8082"
    volumes:
      - email_data:/data
    env_file:
      - .env
    environment:
      - PORT=8082
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  email-checker-app-2:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - "8083"
    volumes:
      - email_data:/data
    env_file:
      - .env
    environment:
      - PORT=8083
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  email-checker-app-3:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - "8084"
    volumes:
      - email_data:/data
    env_file:
      - .env
    environment:
      - PORT=8084
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8084/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  email_data:
    driver: local